name: refreshed_connect
description: "RefreshedConnect is Lightweight HTTP request management package"
version: 1.0.0
repository: "https://github.com/Aniketkhote/refreshed_connect"

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  refreshed: ^1.3.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter: null
